
namespace Win113.Shell.Windows.Special
{
    partial class TaskbarForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(TaskbarForm));
            this.iconsOnTaskbar = new System.Windows.Forms.ImageList(this.components);
            this.taskbarIconsListView = new System.Windows.Forms.ListView();
            this.columnHeader1 = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.statusPanel = new System.Windows.Forms.Panel();
            this.clockLabel = new System.Windows.Forms.Label();
            this.clockTimer = new System.Windows.Forms.Timer(this.components);
            this.configMenu = new System.Windows.Forms.ContextMenuStrip(this.components);
            this.dockToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.topToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.rightToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.bottomToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.leftToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.floatToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.hideDesktopTaskPanelToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.closeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.StartButton = new Win113.Shell.Components.NoSelectButton();
            this.closeButton = new Win113.Shell.Components.NoSelectButton();
            this.statusPanel.SuspendLayout();
            this.configMenu.SuspendLayout();
            this.SuspendLayout();
            // 
            // iconsOnTaskbar
            // 
            this.iconsOnTaskbar.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("iconsOnTaskbar.ImageStream")));
            this.iconsOnTaskbar.TransparentColor = System.Drawing.Color.Transparent;
            this.iconsOnTaskbar.Images.SetKeyName(0, "AB001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(1, "BOCOF001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(2, "BOCOL001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(3, "CALC001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(4, "CARDF001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(5, "CLIPB001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(6, "CLIPB002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(7, "CLIPB003.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(8, "CLIPB004.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(9, "CLIPB005.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(10, "CLIPB006.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(11, "CLOCK001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(12, "CMC001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(13, "CMC002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(14, "CMC003.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(15, "COMMC001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(16, "COMMD001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(17, "COMMD002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(18, "CONTR001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(19, "FAXMG001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(20, "FAXOP001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(21, "FAXVI001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(22, "CHARM001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(23, "KEYVI001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(24, "LOGON001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(25, "MAILS001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(26, "MAILS002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(27, "MAILS003.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(28, "MAILS004.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(29, "MAILS005.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(30, "MAPI001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(31, "MAPI002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(32, "MAPI003.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(33, "MORIC001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(34, "MORIC002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(35, "MORIC003.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(36, "MORIC004.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(37, "MORIC005.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(38, "MORIC006.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(39, "MORIC007.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(40, "MORIC008.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(41, "MORIC009.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(42, "MORIC010.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(43, "MORIC011.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(44, "MORIC012.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(45, "MORIC013.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(46, "MORIC014.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(47, "MORIC015.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(48, "MORIC016.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(49, "MORIC017.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(50, "MORIC018.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(51, "MORIC019.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(52, "MORIC020.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(53, "MORIC021.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(54, "MORIC022.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(55, "MORIC023.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(56, "MORIC024.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(57, "MORIC025.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(58, "MORIC026.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(59, "MORIC027.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(60, "MORIC028.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(61, "MORIC029.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(62, "MORIC030.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(63, "MORIC031.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(64, "MORIC032.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(65, "MORIC033.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(66, "MORIC034.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(67, "MORIC035.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(68, "MORIC036.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(69, "MORIC037.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(70, "MORIC038.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(71, "MORIC039.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(72, "MORIC040.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(73, "MORIC041.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(74, "MORIC042.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(75, "MORIC043.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(76, "MORIC044.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(77, "MORIC045.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(78, "MORIC046.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(79, "MORIC047.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(80, "MORIC048.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(81, "MORIC049.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(82, "MORIC050.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(83, "MORIC051.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(84, "MORIC052.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(85, "MORIC053.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(86, "MORIC054.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(87, "MORIC055.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(88, "MORIC056.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(89, "MORIC057.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(90, "MORIC058.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(91, "MORIC059.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(92, "MORIC060.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(93, "MORIC061.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(94, "MORIC062.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(95, "MORIC063.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(96, "MORIC064.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(97, "MORIC065.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(98, "MORIC066.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(99, "MORIC067.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(100, "MORIC068.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(101, "MORIC069.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(102, "MORIC070.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(103, "MORIC071.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(104, "MORIC072.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(105, "MORIC073.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(106, "MORIC074.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(107, "MORIC075.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(108, "MORIC076.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(109, "MORIC077.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(110, "MORIC078.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(111, "MORIC079.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(112, "MORIC080.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(113, "MORIC081.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(114, "MORIC082.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(115, "MORIC083.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(116, "MORIC084.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(117, "MORIC085.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(118, "MORIC086.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(119, "MORIC087.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(120, "MORIC088.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(121, "MORIC089.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(122, "MORIC090.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(123, "MORIC091.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(124, "MORIC092.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(125, "MORIC093.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(126, "MORIC094.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(127, "MORIC095.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(128, "MORIC096.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(129, "MORIC097.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(130, "MORIC098.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(131, "MORIC099.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(132, "MORIC100.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(133, "MORIC101.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(134, "MORIC102.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(135, "MORIC103.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(136, "MORIC104.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(137, "MORIC105.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(138, "MORIC106.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(139, "MPLAY001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(140, "MSHEA001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(141, "MSMAI001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(142, "MSMAI002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(143, "MSMAI003.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(144, "MSMAI004.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(145, "MSMAI005.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(146, "MSMAI006.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(147, "MSMAI007.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(148, "MSMAI008.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(149, "MSMAI009.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(150, "MSMAI010.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(151, "MSMAI011.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(152, "MSMAI012.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(153, "MSREM001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(154, "NETWA001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(155, "NETWA002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(156, "NOTEP001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(157, "OLE2001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(158, "PACKA001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(159, "PBRUS001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(160, "PIFED001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(161, "PRINT001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(162, "PROGM001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(163, "PROGM002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(164, "PROGM003.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(165, "PROGM004.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(166, "PROGM005.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(167, "PROGM006.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(168, "PROGM007.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(169, "PROGM008.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(170, "PROGM009.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(171, "PROGM010.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(172, "PROGM011.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(173, "PROGM012.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(174, "PROGM013.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(175, "PROGM014.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(176, "PROGM015.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(177, "PROGM016.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(178, "PROGM017.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(179, "PROGM018.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(180, "PROGM019.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(181, "PROGM020.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(182, "PROGM021.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(183, "PROGM022.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(184, "PROGM023.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(185, "PROGM024.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(186, "PROGM025.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(187, "PROGM026.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(188, "PROGM027.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(189, "PROGM028.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(190, "PROGM029.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(191, "PROGM030.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(192, "PROGM031.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(193, "PROGM032.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(194, "PROGM033.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(195, "PROGM034.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(196, "PROGM035.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(197, "PROGM036.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(198, "PROGM037.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(199, "PROGM038.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(200, "PROGM039.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(201, "PROGM040.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(202, "PROGM041.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(203, "PROGM042.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(204, "PROGM043.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(205, "PROGM044.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(206, "PROGM045.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(207, "PROGM046.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(208, "RASST001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(209, "RECOR001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(210, "REGED001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(211, "SCHDP001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(212, "SCHDP002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(213, "SCHDP003.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(214, "SCHDP004.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(215, "SCHDP005.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(216, "SCHDP006.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(217, "SCHDP007.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(218, "SCHDP008.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(219, "SIGVI001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(220, "SOL001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(221, "SOUND001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(222, "STORE001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(223, "SYSED001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(224, "SYSED002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(225, "TERMI001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(226, "UNIDR001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(227, "UNIDR002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(228, "UNIDR003.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(229, "UNIDR004.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(230, "UNIDR005.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(231, "UNIDR006.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(232, "UNIDR007.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(233, "UNIDR008.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(234, "UNINS001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(235, "UNWIS001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(236, "USER001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(237, "VBRUN001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(238, "VBRUN002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(239, "VBRUN003.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(240, "VFORM001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(241, "VFORM002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(242, "VFORM003.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(243, "WFWSE001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(244, "WFWSE002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(245, "WFWSE003.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(246, "WFWSE004.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(247, "WFWSE005.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(248, "WFWSE006.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(249, "WFWSE007.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(250, "WINFI001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(251, "WINFI002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(252, "WINFI003.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(253, "WINFI004.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(254, "WINHE001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(255, "WINHL001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(256, "WINHL002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(257, "WINHL003.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(258, "WINCH001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(259, "WINCH002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(260, "WINCH003.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(261, "WINME001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(262, "WINMI001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(263, "WINPO001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(264, "WINPO002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(265, "WINPO003.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(266, "WINSE001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(267, "WINSE002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(268, "WINSE003.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(269, "WINSE004.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(270, "WINSE005.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(271, "WINTU001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(272, "WINTU002.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(273, "WINTU003.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(274, "WINTU004.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(275, "WINTU005.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(276, "WINTU006.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(277, "WINTU007.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(278, "WINVE001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(279, "WRITE001.ICO");
            this.iconsOnTaskbar.Images.SetKeyName(280, "ac_plug.ico");
            this.iconsOnTaskbar.Images.SetKeyName(281, "accesibility_window_abc.ico");
            this.iconsOnTaskbar.Images.SetKeyName(282, "access_wheelchair_big.ico");
            this.iconsOnTaskbar.Images.SetKeyName(283, "accessibility.ico");
            this.iconsOnTaskbar.Images.SetKeyName(284, "accessibility_big_keys.ico");
            this.iconsOnTaskbar.Images.SetKeyName(285, "accessibility_contrast.ico");
            this.iconsOnTaskbar.Images.SetKeyName(286, "accessibility_kbd_mouse.ico");
            this.iconsOnTaskbar.Images.SetKeyName(287, "accessibility_key_pointer.ico");
            this.iconsOnTaskbar.Images.SetKeyName(288, "accessibility_stopwatch.ico");
            this.iconsOnTaskbar.Images.SetKeyName(289, "accessibility_toggle.ico");
            this.iconsOnTaskbar.Images.SetKeyName(290, "accessibility_toggle2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(291, "accessibility_toggle3.ico");
            this.iconsOnTaskbar.Images.SetKeyName(292, "accessibility_two_windows.ico");
            this.iconsOnTaskbar.Images.SetKeyName(293, "accessibility_window_objs.ico");
            this.iconsOnTaskbar.Images.SetKeyName(294, "accessibility_window_signal.ico");
            this.iconsOnTaskbar.Images.SetKeyName(295, "accessibility_window_speak.ico");
            this.iconsOnTaskbar.Images.SetKeyName(296, "active_movie.ico");
            this.iconsOnTaskbar.Images.SetKeyName(297, "address_book.ico");
            this.iconsOnTaskbar.Images.SetKeyName(298, "address_book_card.ico");
            this.iconsOnTaskbar.Images.SetKeyName(299, "address_book_card_copy.ico");
            this.iconsOnTaskbar.Images.SetKeyName(300, "address_book_card_users.ico");
            this.iconsOnTaskbar.Images.SetKeyName(301, "address_book_cards.ico");
            this.iconsOnTaskbar.Images.SetKeyName(302, "address_book_copy.ico");
            this.iconsOnTaskbar.Images.SetKeyName(303, "address_book_home.ico");
            this.iconsOnTaskbar.Images.SetKeyName(304, "address_book_pad.ico");
            this.iconsOnTaskbar.Images.SetKeyName(305, "address_book_pad_users.ico");
            this.iconsOnTaskbar.Images.SetKeyName(306, "address_book_user.ico");
            this.iconsOnTaskbar.Images.SetKeyName(307, "address_book_users.ico");
            this.iconsOnTaskbar.Images.SetKeyName(308, "amplify.ico");
            this.iconsOnTaskbar.Images.SetKeyName(309, "application_hammer_grouppol.ico");
            this.iconsOnTaskbar.Images.SetKeyName(310, "application_hourglass.ico");
            this.iconsOnTaskbar.Images.SetKeyName(311, "application_hourglass_small.ico");
            this.iconsOnTaskbar.Images.SetKeyName(312, "application_hourglass_small_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(313, "appwiz_file.ico");
            this.iconsOnTaskbar.Images.SetKeyName(314, "appwizard.ico");
            this.iconsOnTaskbar.Images.SetKeyName(315, "appwizard_list.ico");
            this.iconsOnTaskbar.Images.SetKeyName(316, "audio_compression.ico");
            this.iconsOnTaskbar.Images.SetKeyName(317, "backup_devices.ico");
            this.iconsOnTaskbar.Images.SetKeyName(318, "backup_devices_2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(319, "bar_graph.ico");
            this.iconsOnTaskbar.Images.SetKeyName(320, "bar_graph_default.ico");
            this.iconsOnTaskbar.Images.SetKeyName(321, "battery.ico");
            this.iconsOnTaskbar.Images.SetKeyName(322, "battery_alt.ico");
            this.iconsOnTaskbar.Images.SetKeyName(323, "briefcase.ico");
            this.iconsOnTaskbar.Images.SetKeyName(324, "cable.ico");
            this.iconsOnTaskbar.Images.SetKeyName(325, "cable_2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(326, "cable_3.ico");
            this.iconsOnTaskbar.Images.SetKeyName(327, "calculator.ico");
            this.iconsOnTaskbar.Images.SetKeyName(328, "calendar.ico");
            this.iconsOnTaskbar.Images.SetKeyName(329, "calendar2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(330, "camera.ico");
            this.iconsOnTaskbar.Images.SetKeyName(331, "camera_2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(332, "camera_vid.ico");
            this.iconsOnTaskbar.Images.SetKeyName(333, "camera_vid_ms.ico");
            this.iconsOnTaskbar.Images.SetKeyName(334, "camera3.ico");
            this.iconsOnTaskbar.Images.SetKeyName(335, "camera3_network.ico");
            this.iconsOnTaskbar.Images.SetKeyName(336, "camera3_plus.ico");
            this.iconsOnTaskbar.Images.SetKeyName(337, "camera3_vid.ico");
            this.iconsOnTaskbar.Images.SetKeyName(338, "card_reader.ico");
            this.iconsOnTaskbar.Images.SetKeyName(339, "card_reader_empty.ico");
            this.iconsOnTaskbar.Images.SetKeyName(340, "card_reader_not.ico");
            this.iconsOnTaskbar.Images.SetKeyName(341, "card_reader_restr.ico");
            this.iconsOnTaskbar.Images.SetKeyName(342, "cardfile.ico");
            this.iconsOnTaskbar.Images.SetKeyName(343, "cassette_tape.ico");
            this.iconsOnTaskbar.Images.SetKeyName(344, "catalog.ico");
            this.iconsOnTaskbar.Images.SetKeyName(345, "catalog_excl.ico");
            this.iconsOnTaskbar.Images.SetKeyName(346, "catalog_no.ico");
            this.iconsOnTaskbar.Images.SetKeyName(347, "c-clamp.ico");
            this.iconsOnTaskbar.Images.SetKeyName(348, "cd_audio_cd.ico");
            this.iconsOnTaskbar.Images.SetKeyName(349, "cd_audio_cd_a.ico");
            this.iconsOnTaskbar.Images.SetKeyName(350, "cd_drive.ico");
            this.iconsOnTaskbar.Images.SetKeyName(351, "cd_drive_purple.ico");
            this.iconsOnTaskbar.Images.SetKeyName(352, "certificate.ico");
            this.iconsOnTaskbar.Images.SetKeyName(353, "certificate_2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(354, "certificate_2_excl.ico");
            this.iconsOnTaskbar.Images.SetKeyName(355, "certificate_2_no.ico");
            this.iconsOnTaskbar.Images.SetKeyName(356, "certificate_3.ico");
            this.iconsOnTaskbar.Images.SetKeyName(357, "certificate_application.ico");
            this.iconsOnTaskbar.Images.SetKeyName(358, "certificate_envelope_key.ico");
            this.iconsOnTaskbar.Images.SetKeyName(359, "certificate_excl.ico");
            this.iconsOnTaskbar.Images.SetKeyName(360, "certificate_gear.ico");
            this.iconsOnTaskbar.Images.SetKeyName(361, "certificate_checklist.ico");
            this.iconsOnTaskbar.Images.SetKeyName(362, "certificate_multiple.ico");
            this.iconsOnTaskbar.Images.SetKeyName(363, "certificate_no.ico");
            this.iconsOnTaskbar.Images.SetKeyName(364, "certificate_red_line.ico");
            this.iconsOnTaskbar.Images.SetKeyName(365, "certificate_seal.ico");
            this.iconsOnTaskbar.Images.SetKeyName(366, "certificate_seal_lock.ico");
            this.iconsOnTaskbar.Images.SetKeyName(367, "certificate_server.ico");
            this.iconsOnTaskbar.Images.SetKeyName(368, "circle_question.ico");
            this.iconsOnTaskbar.Images.SetKeyName(369, "clean_drive.ico");
            this.iconsOnTaskbar.Images.SetKeyName(370, "clock.ico");
            this.iconsOnTaskbar.Images.SetKeyName(371, "color_profile.ico");
            this.iconsOnTaskbar.Images.SetKeyName(372, "color_profile_gray.ico");
            this.iconsOnTaskbar.Images.SetKeyName(373, "computer.ico");
            this.iconsOnTaskbar.Images.SetKeyName(374, "computer_2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(375, "computer_2_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(376, "computer_explorer.ico");
            this.iconsOnTaskbar.Images.SetKeyName(377, "computer_explorer_2k.ico");
            this.iconsOnTaskbar.Images.SetKeyName(378, "computer_explorer_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(379, "computer_gear.ico");
            this.iconsOnTaskbar.Images.SetKeyName(380, "computer_musical_keyboard.ico");
            this.iconsOnTaskbar.Images.SetKeyName(381, "computer_padlock.ico");
            this.iconsOnTaskbar.Images.SetKeyName(382, "computer_search.ico");
            this.iconsOnTaskbar.Images.SetKeyName(383, "computer_sound.ico");
            this.iconsOnTaskbar.Images.SetKeyName(384, "computer_taskmgr.ico");
            this.iconsOnTaskbar.Images.SetKeyName(385, "computer_user_pencil.ico");
            this.iconsOnTaskbar.Images.SetKeyName(386, "computer_win.ico");
            this.iconsOnTaskbar.Images.SetKeyName(387, "computer_win_lock.ico");
            this.iconsOnTaskbar.Images.SetKeyName(388, "conn_cloud.ico");
            this.iconsOnTaskbar.Images.SetKeyName(389, "conn_cloud_ok.ico");
            this.iconsOnTaskbar.Images.SetKeyName(390, "conn_dialup.ico");
            this.iconsOnTaskbar.Images.SetKeyName(391, "conn_dialup_alt.ico");
            this.iconsOnTaskbar.Images.SetKeyName(392, "conn_dialup_ok.ico");
            this.iconsOnTaskbar.Images.SetKeyName(393, "conn_dialup_recbin_phone.ico");
            this.iconsOnTaskbar.Images.SetKeyName(394, "conn_dialup_recbin_phones.ico");
            this.iconsOnTaskbar.Images.SetKeyName(395, "conn_network_no_phone.ico");
            this.iconsOnTaskbar.Images.SetKeyName(396, "conn_pcs_no_network.ico");
            this.iconsOnTaskbar.Images.SetKeyName(397, "conn_pcs_off_off.ico");
            this.iconsOnTaskbar.Images.SetKeyName(398, "conn_pcs_off_on.ico");
            this.iconsOnTaskbar.Images.SetKeyName(399, "conn_pcs_on_off.ico");
            this.iconsOnTaskbar.Images.SetKeyName(400, "conn_pcs_on_on.ico");
            this.iconsOnTaskbar.Images.SetKeyName(401, "connected_world.ico");
            this.iconsOnTaskbar.Images.SetKeyName(402, "console_prompt.ico");
            this.iconsOnTaskbar.Images.SetKeyName(403, "cylinder_database.ico");
            this.iconsOnTaskbar.Images.SetKeyName(404, "defragment.ico");
            this.iconsOnTaskbar.Images.SetKeyName(405, "desktop.ico");
            this.iconsOnTaskbar.Images.SetKeyName(406, "desktop_old.ico");
            this.iconsOnTaskbar.Images.SetKeyName(407, "desktop_w95.ico");
            this.iconsOnTaskbar.Images.SetKeyName(408, "device_rhombic_chip.ico");
            this.iconsOnTaskbar.Images.SetKeyName(409, "direct_cable_conn.ico");
            this.iconsOnTaskbar.Images.SetKeyName(410, "directory_admin_tools.ico");
            this.iconsOnTaskbar.Images.SetKeyName(411, "directory_business_calendar.ico");
            this.iconsOnTaskbar.Images.SetKeyName(412, "directory_closed.ico");
            this.iconsOnTaskbar.Images.SetKeyName(413, "directory_closed_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(414, "directory_closed_history.ico");
            this.iconsOnTaskbar.Images.SetKeyName(415, "directory_computer.ico");
            this.iconsOnTaskbar.Images.SetKeyName(416, "directory_control_panel.ico");
            this.iconsOnTaskbar.Images.SetKeyName(417, "directory_control_panel_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(418, "directory_dial-up_networking.ico");
            this.iconsOnTaskbar.Images.SetKeyName(419, "directory_dial-up_networking_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(420, "directory_e.ico");
            this.iconsOnTaskbar.Images.SetKeyName(421, "directory_e_open.ico");
            this.iconsOnTaskbar.Images.SetKeyName(422, "directory_explorer.ico");
            this.iconsOnTaskbar.Images.SetKeyName(423, "directory_favorites.ico");
            this.iconsOnTaskbar.Images.SetKeyName(424, "directory_favorites_small.ico");
            this.iconsOnTaskbar.Images.SetKeyName(425, "directory_folder_options.ico");
            this.iconsOnTaskbar.Images.SetKeyName(426, "directory_fonts.ico");
            this.iconsOnTaskbar.Images.SetKeyName(427, "directory_fonts_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(428, "directory_fonts_shortcut.ico");
            this.iconsOnTaskbar.Images.SetKeyName(429, "directory_channels.ico");
            this.iconsOnTaskbar.Images.SetKeyName(430, "directory_check.ico");
            this.iconsOnTaskbar.Images.SetKeyName(431, "directory_movie.ico");
            this.iconsOnTaskbar.Images.SetKeyName(432, "directory_net_web.ico");
            this.iconsOnTaskbar.Images.SetKeyName(433, "directory_network_conn.ico");
            this.iconsOnTaskbar.Images.SetKeyName(434, "directory_network_conn_shortcut.ico");
            this.iconsOnTaskbar.Images.SetKeyName(435, "directory_open.ico");
            this.iconsOnTaskbar.Images.SetKeyName(436, "directory_open_cabinet.ico");
            this.iconsOnTaskbar.Images.SetKeyName(437, "directory_open_cabinet_fc.ico");
            this.iconsOnTaskbar.Images.SetKeyName(438, "directory_open_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(439, "directory_open_file_mydocs.ico");
            this.iconsOnTaskbar.Images.SetKeyName(440, "directory_open_file_mydocs_2k.ico");
            this.iconsOnTaskbar.Images.SetKeyName(441, "directory_open_file_mydocs_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(442, "directory_open_file_mydocs_small.ico");
            this.iconsOnTaskbar.Images.SetKeyName(443, "directory_open_history.ico");
            this.iconsOnTaskbar.Images.SetKeyName(444, "directory_open_net_web_documents.ico");
            this.iconsOnTaskbar.Images.SetKeyName(445, "directory_open_network.ico");
            this.iconsOnTaskbar.Images.SetKeyName(446, "directory_open_refresh.ico");
            this.iconsOnTaskbar.Images.SetKeyName(447, "directory_pictures.ico");
            this.iconsOnTaskbar.Images.SetKeyName(448, "directory_printer.ico");
            this.iconsOnTaskbar.Images.SetKeyName(449, "directory_printer_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(450, "directory_printer_shortcut.ico");
            this.iconsOnTaskbar.Images.SetKeyName(451, "directory_program_group.ico");
            this.iconsOnTaskbar.Images.SetKeyName(452, "directory_program_group_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(453, "directory_program_group_small.ico");
            this.iconsOnTaskbar.Images.SetKeyName(454, "directory_program_group_small_c.ico");
            this.iconsOnTaskbar.Images.SetKeyName(455, "directory_scanner_camera.ico");
            this.iconsOnTaskbar.Images.SetKeyName(456, "directory_seven.ico");
            this.iconsOnTaskbar.Images.SetKeyName(457, "directory_shared.ico");
            this.iconsOnTaskbar.Images.SetKeyName(458, "directory_sched_tasks.ico");
            this.iconsOnTaskbar.Images.SetKeyName(459, "directory_web.ico");
            this.iconsOnTaskbar.Images.SetKeyName(460, "directory_zipper.ico");
            this.iconsOnTaskbar.Images.SetKeyName(461, "directory_zipper_alt.ico");
            this.iconsOnTaskbar.Images.SetKeyName(462, "directx.ico");
            this.iconsOnTaskbar.Images.SetKeyName(463, "directx_alt.ico");
            this.iconsOnTaskbar.Images.SetKeyName(464, "diskettes_copy.ico");
            this.iconsOnTaskbar.Images.SetKeyName(465, "display_properties.ico");
            this.iconsOnTaskbar.Images.SetKeyName(466, "doctor_watson.ico");
            this.iconsOnTaskbar.Images.SetKeyName(467, "document.ico");
            this.iconsOnTaskbar.Images.SetKeyName(468, "download.ico");
            this.iconsOnTaskbar.Images.SetKeyName(469, "drum_onestick.ico");
            this.iconsOnTaskbar.Images.SetKeyName(470, "eject_pc.ico");
            this.iconsOnTaskbar.Images.SetKeyName(471, "eject_pc_2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(472, "eject_pc_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(473, "eject_pc_shell32.ico");
            this.iconsOnTaskbar.Images.SetKeyName(474, "entire_network_globe.ico");
            this.iconsOnTaskbar.Images.SetKeyName(475, "envelope_closed.ico");
            this.iconsOnTaskbar.Images.SetKeyName(476, "envelope_open_sheet.ico");
            this.iconsOnTaskbar.Images.SetKeyName(477, "erase_file.ico");
            this.iconsOnTaskbar.Images.SetKeyName(478, "event_log.ico");
            this.iconsOnTaskbar.Images.SetKeyName(479, "executable.ico");
            this.iconsOnTaskbar.Images.SetKeyName(480, "executable_gear.ico");
            this.iconsOnTaskbar.Images.SetKeyName(481, "executable_script.ico");
            this.iconsOnTaskbar.Images.SetKeyName(482, "executable_sound.ico");
            this.iconsOnTaskbar.Images.SetKeyName(483, "expand_hierarchial_array.ico");
            this.iconsOnTaskbar.Images.SetKeyName(484, "expansion_board.ico");
            this.iconsOnTaskbar.Images.SetKeyName(485, "expansion_board_modem.ico");
            this.iconsOnTaskbar.Images.SetKeyName(486, "fax_machine.ico");
            this.iconsOnTaskbar.Images.SetKeyName(487, "fax_machine_exclam.ico");
            this.iconsOnTaskbar.Images.SetKeyName(488, "fax_machine_paperstack.ico");
            this.iconsOnTaskbar.Images.SetKeyName(489, "file_blue_grad_paint.ico");
            this.iconsOnTaskbar.Images.SetKeyName(490, "file_cd.ico");
            this.iconsOnTaskbar.Images.SetKeyName(491, "file_eye.ico");
            this.iconsOnTaskbar.Images.SetKeyName(492, "file_gears.ico");
            this.iconsOnTaskbar.Images.SetKeyName(493, "file_lines.ico");
            this.iconsOnTaskbar.Images.SetKeyName(494, "file_padlock.ico");
            this.iconsOnTaskbar.Images.SetKeyName(495, "file_program_group.ico");
            this.iconsOnTaskbar.Images.SetKeyName(496, "file_question.ico");
            this.iconsOnTaskbar.Images.SetKeyName(497, "file_set.ico");
            this.iconsOnTaskbar.Images.SetKeyName(498, "file_sorted_lock.ico");
            this.iconsOnTaskbar.Images.SetKeyName(499, "file_win_shortcut.ico");
            this.iconsOnTaskbar.Images.SetKeyName(500, "file_windows.ico");
            this.iconsOnTaskbar.Images.SetKeyName(501, "filepack.ico");
            this.iconsOnTaskbar.Images.SetKeyName(502, "floppy_drive_3-5.ico");
            this.iconsOnTaskbar.Images.SetKeyName(503, "floppy_drive_3-5_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(504, "floppy_drive_5-25.ico");
            this.iconsOnTaskbar.Images.SetKeyName(505, "floppy_drive_5-25_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(506, "font_adobe.ico");
            this.iconsOnTaskbar.Images.SetKeyName(507, "font_bitmap.ico");
            this.iconsOnTaskbar.Images.SetKeyName(508, "font_opentype.ico");
            this.iconsOnTaskbar.Images.SetKeyName(509, "font_tt.ico");
            this.iconsOnTaskbar.Images.SetKeyName(510, "font_tt_green.ico");
            this.iconsOnTaskbar.Images.SetKeyName(511, "frame_web.ico");
            this.iconsOnTaskbar.Images.SetKeyName(512, "game_freecell.ico");
            this.iconsOnTaskbar.Images.SetKeyName(513, "game_hearts.ico");
            this.iconsOnTaskbar.Images.SetKeyName(514, "game_mine_1.ico");
            this.iconsOnTaskbar.Images.SetKeyName(515, "game_mine_2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(516, "game_solitaire.ico");
            this.iconsOnTaskbar.Images.SetKeyName(517, "game_spider.ico");
            this.iconsOnTaskbar.Images.SetKeyName(518, "gears.ico");
            this.iconsOnTaskbar.Images.SetKeyName(519, "gears_3.ico");
            this.iconsOnTaskbar.Images.SetKeyName(520, "gears_tweakui_a.ico");
            this.iconsOnTaskbar.Images.SetKeyName(521, "gears_tweakui_b.ico");
            this.iconsOnTaskbar.Images.SetKeyName(522, "globe_map.ico");
            this.iconsOnTaskbar.Images.SetKeyName(523, "gps.ico");
            this.iconsOnTaskbar.Images.SetKeyName(524, "graphedit.ico");
            this.iconsOnTaskbar.Images.SetKeyName(525, "graphedit_file.ico");
            this.iconsOnTaskbar.Images.SetKeyName(526, "graphedit_file_2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(527, "hard_disk_drive.ico");
            this.iconsOnTaskbar.Images.SetKeyName(528, "hard_disk_drive_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(529, "hard_disk_drive_pie.ico");
            this.iconsOnTaskbar.Images.SetKeyName(530, "hard_disk_drive_tools.ico");
            this.iconsOnTaskbar.Images.SetKeyName(531, "hard_disk_drives.ico");
            this.iconsOnTaskbar.Images.SetKeyName(532, "hardware.ico");
            this.iconsOnTaskbar.Images.SetKeyName(533, "help_book_big.ico");
            this.iconsOnTaskbar.Images.SetKeyName(534, "help_book_computer.ico");
            this.iconsOnTaskbar.Images.SetKeyName(535, "help_book_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(536, "help_book_cool_small.ico");
            this.iconsOnTaskbar.Images.SetKeyName(537, "help_book_small.ico");
            this.iconsOnTaskbar.Images.SetKeyName(538, "help_question_mark.ico");
            this.iconsOnTaskbar.Images.SetKeyName(539, "help_sheet.ico");
            this.iconsOnTaskbar.Images.SetKeyName(540, "history.ico");
            this.iconsOnTaskbar.Images.SetKeyName(541, "homepage.ico");
            this.iconsOnTaskbar.Images.SetKeyName(542, "homepage_alt.ico");
            this.iconsOnTaskbar.Images.SetKeyName(543, "html.ico");
            this.iconsOnTaskbar.Images.SetKeyName(544, "html2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(545, "html2_new.ico");
            this.iconsOnTaskbar.Images.SetKeyName(546, "channels.ico");
            this.iconsOnTaskbar.Images.SetKeyName(547, "channels_file.ico");
            this.iconsOnTaskbar.Images.SetKeyName(548, "charmap.ico");
            this.iconsOnTaskbar.Images.SetKeyName(549, "charmap_w2k.ico");
            this.iconsOnTaskbar.Images.SetKeyName(550, "chart1.ico");
            this.iconsOnTaskbar.Images.SetKeyName(551, "check.ico");
            this.iconsOnTaskbar.Images.SetKeyName(552, "chip_ramdrive.ico");
            this.iconsOnTaskbar.Images.SetKeyName(553, "chm.ico");
            this.iconsOnTaskbar.Images.SetKeyName(554, "image_old_gif.ico");
            this.iconsOnTaskbar.Images.SetKeyName(555, "image_old_jpeg.ico");
            this.iconsOnTaskbar.Images.SetKeyName(556, "imagGIF.ico");
            this.iconsOnTaskbar.Images.SetKeyName(557, "imagJPEG.ico");
            this.iconsOnTaskbar.Images.SetKeyName(558, "imagKoda.ico");
            this.iconsOnTaskbar.Images.SetKeyName(559, "imagOthe.ico");
            this.iconsOnTaskbar.Images.SetKeyName(560, "imagPNG.ico");
            this.iconsOnTaskbar.Images.SetKeyName(561, "imagWMF.ico");
            this.iconsOnTaskbar.Images.SetKeyName(562, "infrared.ico");
            this.iconsOnTaskbar.Images.SetKeyName(563, "input_devices.ico");
            this.iconsOnTaskbar.Images.SetKeyName(564, "installer.ico");
            this.iconsOnTaskbar.Images.SetKeyName(565, "installer_file_gear.ico");
            this.iconsOnTaskbar.Images.SetKeyName(566, "installer_generic_old.ico");
            this.iconsOnTaskbar.Images.SetKeyName(567, "internet_connection_wiz.ico");
            this.iconsOnTaskbar.Images.SetKeyName(568, "internet_options.ico");
            this.iconsOnTaskbar.Images.SetKeyName(569, "internet_options_old_e.ico");
            this.iconsOnTaskbar.Images.SetKeyName(570, "ipconfig.ico");
            this.iconsOnTaskbar.Images.SetKeyName(571, "java.ico");
            this.iconsOnTaskbar.Images.SetKeyName(572, "java_dpf.ico");
            this.iconsOnTaskbar.Images.SetKeyName(573, "java_ocx.ico");
            this.iconsOnTaskbar.Images.SetKeyName(574, "joystick.ico");
            this.iconsOnTaskbar.Images.SetKeyName(575, "joystick_alt.ico");
            this.iconsOnTaskbar.Images.SetKeyName(576, "joystick_button.ico");
            this.iconsOnTaskbar.Images.SetKeyName(577, "key_gray.ico");
            this.iconsOnTaskbar.Images.SetKeyName(578, "key_padlock.ico");
            this.iconsOnTaskbar.Images.SetKeyName(579, "key_padlock_help.ico");
            this.iconsOnTaskbar.Images.SetKeyName(580, "key_webfile.ico");
            this.iconsOnTaskbar.Images.SetKeyName(581, "key_win.ico");
            this.iconsOnTaskbar.Images.SetKeyName(582, "key_win_alt.ico");
            this.iconsOnTaskbar.Images.SetKeyName(583, "key_world.ico");
            this.iconsOnTaskbar.Images.SetKeyName(584, "keyboard.ico");
            this.iconsOnTaskbar.Images.SetKeyName(585, "keyboard_delay.ico");
            this.iconsOnTaskbar.Images.SetKeyName(586, "keyboard_musical.ico");
            this.iconsOnTaskbar.Images.SetKeyName(587, "keyboard_musical_midi.ico");
            this.iconsOnTaskbar.Images.SetKeyName(588, "keyboard_repeat_rate.ico");
            this.iconsOnTaskbar.Images.SetKeyName(589, "keys.ico");
            this.iconsOnTaskbar.Images.SetKeyName(590, "kodak_imaging.ico");
            this.iconsOnTaskbar.Images.SetKeyName(591, "kodak_imaging_file.ico");
            this.iconsOnTaskbar.Images.SetKeyName(592, "laptop.ico");
            this.iconsOnTaskbar.Images.SetKeyName(593, "laptop_infrared.ico");
            this.iconsOnTaskbar.Images.SetKeyName(594, "laptop_infrared_2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(595, "laptop_small.ico");
            this.iconsOnTaskbar.Images.SetKeyName(596, "loudspeaker_muted.ico");
            this.iconsOnTaskbar.Images.SetKeyName(597, "loudspeaker_rays.ico");
            this.iconsOnTaskbar.Images.SetKeyName(598, "loudspeaker_rays_green.ico");
            this.iconsOnTaskbar.Images.SetKeyName(599, "loudspeaker_wave.ico");
            this.iconsOnTaskbar.Images.SetKeyName(600, "magnifying_glass.ico");
            this.iconsOnTaskbar.Images.SetKeyName(601, "magnifying_glass_3.ico");
            this.iconsOnTaskbar.Images.SetKeyName(602, "magnifying_glass_4.ico");
            this.iconsOnTaskbar.Images.SetKeyName(603, "mailbox_world.ico");
            this.iconsOnTaskbar.Images.SetKeyName(604, "mci_devices.ico");
            this.iconsOnTaskbar.Images.SetKeyName(605, "media_player.ico");
            this.iconsOnTaskbar.Images.SetKeyName(606, "media_player_file.ico");
            this.iconsOnTaskbar.Images.SetKeyName(607, "media_player_stream_conn1.ico");
            this.iconsOnTaskbar.Images.SetKeyName(608, "media_player_stream_conn2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(609, "media_player_stream_mono.ico");
            this.iconsOnTaskbar.Images.SetKeyName(610, "media_player_stream_no.ico");
            this.iconsOnTaskbar.Images.SetKeyName(611, "media_player_stream_no2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(612, "media_player_stream_stereo.ico");
            this.iconsOnTaskbar.Images.SetKeyName(613, "media_player_stream_sun0.ico");
            this.iconsOnTaskbar.Images.SetKeyName(614, "media_player_stream_sun1.ico");
            this.iconsOnTaskbar.Images.SetKeyName(615, "media_player_stream_sun2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(616, "media_player_stream_sun3.ico");
            this.iconsOnTaskbar.Images.SetKeyName(617, "media_player_stream_sun4.ico");
            this.iconsOnTaskbar.Images.SetKeyName(618, "memory.ico");
            this.iconsOnTaskbar.Images.SetKeyName(619, "message_empty_tack.ico");
            this.iconsOnTaskbar.Images.SetKeyName(620, "message_envelope_open.ico");
            this.iconsOnTaskbar.Images.SetKeyName(621, "message_file.ico");
            this.iconsOnTaskbar.Images.SetKeyName(622, "message_tack.ico");
            this.iconsOnTaskbar.Images.SetKeyName(623, "microphone.ico");
            this.iconsOnTaskbar.Images.SetKeyName(624, "microphone_2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(625, "midi_bl.ico");
            this.iconsOnTaskbar.Images.SetKeyName(626, "midi_gr.ico");
            this.iconsOnTaskbar.Images.SetKeyName(627, "midi_mg.ico");
            this.iconsOnTaskbar.Images.SetKeyName(628, "midi_tl.ico");
            this.iconsOnTaskbar.Images.SetKeyName(629, "minesweeper.ico");
            this.iconsOnTaskbar.Images.SetKeyName(630, "mixer_cd_sound.ico");
            this.iconsOnTaskbar.Images.SetKeyName(631, "mixer_keyboard_musical.ico");
            this.iconsOnTaskbar.Images.SetKeyName(632, "mixer_sound.ico");
            this.iconsOnTaskbar.Images.SetKeyName(633, "modem.ico");
            this.iconsOnTaskbar.Images.SetKeyName(634, "monitor_application.ico");
            this.iconsOnTaskbar.Images.SetKeyName(635, "monitor_black.ico");
            this.iconsOnTaskbar.Images.SetKeyName(636, "monitor_blue_grad.ico");
            this.iconsOnTaskbar.Images.SetKeyName(637, "monitor_gear.ico");
            this.iconsOnTaskbar.Images.SetKeyName(638, "monitor_moon.ico");
            this.iconsOnTaskbar.Images.SetKeyName(639, "monitor_tweakui.ico");
            this.iconsOnTaskbar.Images.SetKeyName(640, "monitor_windows.ico");
            this.iconsOnTaskbar.Images.SetKeyName(641, "mouse.ico");
            this.iconsOnTaskbar.Images.SetKeyName(642, "mouse_hide.ico");
            this.iconsOnTaskbar.Images.SetKeyName(643, "mouse_location.ico");
            this.iconsOnTaskbar.Images.SetKeyName(644, "mouse_ms.ico");
            this.iconsOnTaskbar.Images.SetKeyName(645, "mouse_padlock.ico");
            this.iconsOnTaskbar.Images.SetKeyName(646, "mouse_snap.ico");
            this.iconsOnTaskbar.Images.SetKeyName(647, "mouse_speed.ico");
            this.iconsOnTaskbar.Images.SetKeyName(648, "mouse_trails.ico");
            this.iconsOnTaskbar.Images.SetKeyName(649, "mouse_wireless.ico");
            this.iconsOnTaskbar.Images.SetKeyName(650, "move_system_file.ico");
            this.iconsOnTaskbar.Images.SetKeyName(651, "movie_maker.ico");
            this.iconsOnTaskbar.Images.SetKeyName(652, "msagent.ico");
            this.iconsOnTaskbar.Images.SetKeyName(653, "msagent_file.ico");
            this.iconsOnTaskbar.Images.SetKeyName(654, "msconfig.ico");
            this.iconsOnTaskbar.Images.SetKeyName(655, "ms-dos.ico");
            this.iconsOnTaskbar.Images.SetKeyName(656, "ms-dos_2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(657, "msg_error.ico");
            this.iconsOnTaskbar.Images.SetKeyName(658, "msg_information.ico");
            this.iconsOnTaskbar.Images.SetKeyName(659, "msg_question.ico");
            this.iconsOnTaskbar.Images.SetKeyName(660, "msg_warning.ico");
            this.iconsOnTaskbar.Images.SetKeyName(661, "msg_warning_inv.ico");
            this.iconsOnTaskbar.Images.SetKeyName(662, "mshearts.ico");
            this.iconsOnTaskbar.Images.SetKeyName(663, "msie_box.ico");
            this.iconsOnTaskbar.Images.SetKeyName(664, "msie1.ico");
            this.iconsOnTaskbar.Images.SetKeyName(665, "msie2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(666, "msinfo32.ico");
            this.iconsOnTaskbar.Images.SetKeyName(667, "msn.ico");
            this.iconsOnTaskbar.Images.SetKeyName(668, "msn_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(669, "msn2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(670, "msn3.ico");
            this.iconsOnTaskbar.Images.SetKeyName(671, "multimedia.ico");
            this.iconsOnTaskbar.Images.SetKeyName(672, "nail.ico");
            this.iconsOnTaskbar.Images.SetKeyName(673, "netmeeting.ico");
            this.iconsOnTaskbar.Images.SetKeyName(674, "netmeeting_share.ico");
            this.iconsOnTaskbar.Images.SetKeyName(675, "netshow.ico");
            this.iconsOnTaskbar.Images.SetKeyName(676, "netshow_arrow.ico");
            this.iconsOnTaskbar.Images.SetKeyName(677, "netshow_notransm.ico");
            this.iconsOnTaskbar.Images.SetKeyName(678, "network.ico");
            this.iconsOnTaskbar.Images.SetKeyName(679, "network_cool_two_pcs.ico");
            this.iconsOnTaskbar.Images.SetKeyName(680, "network_drive.ico");
            this.iconsOnTaskbar.Images.SetKeyName(681, "network_drive_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(682, "network_drive_unavailable.ico");
            this.iconsOnTaskbar.Images.SetKeyName(683, "network_drive_unavailable_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(684, "network_drive_world.ico");
            this.iconsOnTaskbar.Images.SetKeyName(685, "network_internet_pcs_installer.ico");
            this.iconsOnTaskbar.Images.SetKeyName(686, "network_normal_two_pcs.ico");
            this.iconsOnTaskbar.Images.SetKeyName(687, "network_television.ico");
            this.iconsOnTaskbar.Images.SetKeyName(688, "network_televisons.ico");
            this.iconsOnTaskbar.Images.SetKeyName(689, "network_three_pcs.ico");
            this.iconsOnTaskbar.Images.SetKeyName(690, "newspaper.ico");
            this.iconsOnTaskbar.Images.SetKeyName(691, "newspaper_mail.ico");
            this.iconsOnTaskbar.Images.SetKeyName(692, "no.ico");
            this.iconsOnTaskbar.Images.SetKeyName(693, "no2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(694, "note.ico");
            this.iconsOnTaskbar.Images.SetKeyName(695, "notepad.ico");
            this.iconsOnTaskbar.Images.SetKeyName(696, "notepad_file.ico");
            this.iconsOnTaskbar.Images.SetKeyName(697, "notepad_file_gear.ico");
            this.iconsOnTaskbar.Images.SetKeyName(698, "odbc.ico");
            this.iconsOnTaskbar.Images.SetKeyName(699, "ole.ico");
            this.iconsOnTaskbar.Images.SetKeyName(700, "ole2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(701, "outlook_express.ico");
            this.iconsOnTaskbar.Images.SetKeyName(702, "outlook_express_tack.ico");
            this.iconsOnTaskbar.Images.SetKeyName(703, "outlook_express_tack_drive.ico");
            this.iconsOnTaskbar.Images.SetKeyName(704, "outlook_express_tack_folder.ico");
            this.iconsOnTaskbar.Images.SetKeyName(705, "overlay_black.ico");
            this.iconsOnTaskbar.Images.SetKeyName(706, "overlay_refresh.ico");
            this.iconsOnTaskbar.Images.SetKeyName(707, "overlay_share.ico");
            this.iconsOnTaskbar.Images.SetKeyName(708, "overlay_share_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(709, "overlay_shortcut.ico");
            this.iconsOnTaskbar.Images.SetKeyName(710, "package.ico");
            this.iconsOnTaskbar.Images.SetKeyName(711, "paint.ico");
            this.iconsOnTaskbar.Images.SetKeyName(712, "paint_file.ico");
            this.iconsOnTaskbar.Images.SetKeyName(713, "paint_old.ico");
            this.iconsOnTaskbar.Images.SetKeyName(714, "paint_window.ico");
            this.iconsOnTaskbar.Images.SetKeyName(715, "paintbrush.ico");
            this.iconsOnTaskbar.Images.SetKeyName(716, "palm_computer.ico");
            this.iconsOnTaskbar.Images.SetKeyName(717, "paper_roll.ico");
            this.iconsOnTaskbar.Images.SetKeyName(718, "pci_card.ico");
            this.iconsOnTaskbar.Images.SetKeyName(719, "pci_card_alt.ico");
            this.iconsOnTaskbar.Images.SetKeyName(720, "pcx.ico");
            this.iconsOnTaskbar.Images.SetKeyName(721, "pcx_alt.ico");
            this.iconsOnTaskbar.Images.SetKeyName(722, "phone_desk.ico");
            this.iconsOnTaskbar.Images.SetKeyName(723, "pictures.ico");
            this.iconsOnTaskbar.Images.SetKeyName(724, "pie_chart_drvspace.ico");
            this.iconsOnTaskbar.Images.SetKeyName(725, "pifedit.ico");
            this.iconsOnTaskbar.Images.SetKeyName(726, "power_management.ico");
            this.iconsOnTaskbar.Images.SetKeyName(727, "print_server.ico");
            this.iconsOnTaskbar.Images.SetKeyName(728, "printer.ico");
            this.iconsOnTaskbar.Images.SetKeyName(729, "printer_big.ico");
            this.iconsOnTaskbar.Images.SetKeyName(730, "printer_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(731, "printer_def.ico");
            this.iconsOnTaskbar.Images.SetKeyName(732, "printer_def_diskette.ico");
            this.iconsOnTaskbar.Images.SetKeyName(733, "printer_def_network.ico");
            this.iconsOnTaskbar.Images.SetKeyName(734, "printer_desk.ico");
            this.iconsOnTaskbar.Images.SetKeyName(735, "printer_diskette.ico");
            this.iconsOnTaskbar.Images.SetKeyName(736, "printer_feeding_slot.ico");
            this.iconsOnTaskbar.Images.SetKeyName(737, "printer_network.ico");
            this.iconsOnTaskbar.Images.SetKeyName(738, "printer_pause.ico");
            this.iconsOnTaskbar.Images.SetKeyName(739, "printer_play.ico");
            this.iconsOnTaskbar.Images.SetKeyName(740, "printer_plotter.ico");
            this.iconsOnTaskbar.Images.SetKeyName(741, "printer_question.ico");
            this.iconsOnTaskbar.Images.SetKeyName(742, "printer_shared.ico");
            this.iconsOnTaskbar.Images.SetKeyName(743, "printer_slim.ico");
            this.iconsOnTaskbar.Images.SetKeyName(744, "printer_slot_filled.ico");
            this.iconsOnTaskbar.Images.SetKeyName(745, "processor.ico");
            this.iconsOnTaskbar.Images.SetKeyName(746, "program_manager.ico");
            this.iconsOnTaskbar.Images.SetKeyName(747, "ram_drive.ico");
            this.iconsOnTaskbar.Images.SetKeyName(748, "recycle_bin_directory.ico");
            this.iconsOnTaskbar.Images.SetKeyName(749, "recycle_bin_empty.ico");
            this.iconsOnTaskbar.Images.SetKeyName(750, "recycle_bin_empty_2k.ico");
            this.iconsOnTaskbar.Images.SetKeyName(751, "recycle_bin_empty_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(752, "recycle_bin_file.ico");
            this.iconsOnTaskbar.Images.SetKeyName(753, "recycle_bin_file_directory.ico");
            this.iconsOnTaskbar.Images.SetKeyName(754, "recycle_bin_full.ico");
            this.iconsOnTaskbar.Images.SetKeyName(755, "recycle_bin_full_2k.ico");
            this.iconsOnTaskbar.Images.SetKeyName(756, "recycle_bin_full_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(757, "regedit.ico");
            this.iconsOnTaskbar.Images.SetKeyName(758, "regedit_binary.ico");
            this.iconsOnTaskbar.Images.SetKeyName(759, "regedit_binary_lock.ico");
            this.iconsOnTaskbar.Images.SetKeyName(760, "regedit_file.ico");
            this.iconsOnTaskbar.Images.SetKeyName(761, "regedit_string.ico");
            this.iconsOnTaskbar.Images.SetKeyName(762, "registration.ico");
            this.iconsOnTaskbar.Images.SetKeyName(763, "registration_no.ico");
            this.iconsOnTaskbar.Images.SetKeyName(764, "removable_disk_drive.ico");
            this.iconsOnTaskbar.Images.SetKeyName(765, "removable_disk_drive_alt.ico");
            this.iconsOnTaskbar.Images.SetKeyName(766, "rename.ico");
            this.iconsOnTaskbar.Images.SetKeyName(767, "replace_directory.ico");
            this.iconsOnTaskbar.Images.SetKeyName(768, "replace_file.ico");
            this.iconsOnTaskbar.Images.SetKeyName(769, "restrict.ico");
            this.iconsOnTaskbar.Images.SetKeyName(770, "rj_jack.ico");
            this.iconsOnTaskbar.Images.SetKeyName(771, "Roland_GS.ico");
            this.iconsOnTaskbar.Images.SetKeyName(772, "scandisk.ico");
            this.iconsOnTaskbar.Images.SetKeyName(773, "scanner.ico");
            this.iconsOnTaskbar.Images.SetKeyName(774, "scanner_alt.ico");
            this.iconsOnTaskbar.Images.SetKeyName(775, "scanner_alt_network.ico");
            this.iconsOnTaskbar.Images.SetKeyName(776, "scanner_camera.ico");
            this.iconsOnTaskbar.Images.SetKeyName(777, "scanner_video_cam.ico");
            this.iconsOnTaskbar.Images.SetKeyName(778, "scanregw.ico");
            this.iconsOnTaskbar.Images.SetKeyName(779, "screen_keyboard.ico");
            this.iconsOnTaskbar.Images.SetKeyName(780, "script_file_blue.ico");
            this.iconsOnTaskbar.Images.SetKeyName(781, "script_file_teal.ico");
            this.iconsOnTaskbar.Images.SetKeyName(782, "script_file_yellow.ico");
            this.iconsOnTaskbar.Images.SetKeyName(783, "scsi.ico");
            this.iconsOnTaskbar.Images.SetKeyName(784, "search_computer.ico");
            this.iconsOnTaskbar.Images.SetKeyName(785, "search_directory.ico");
            this.iconsOnTaskbar.Images.SetKeyName(786, "search_file.ico");
            this.iconsOnTaskbar.Images.SetKeyName(787, "search_file_2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(788, "search_file_2_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(789, "search_file_3.ico");
            this.iconsOnTaskbar.Images.SetKeyName(790, "search_laptop_1.ico");
            this.iconsOnTaskbar.Images.SetKeyName(791, "search_laptop_2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(792, "search_laptop_3.ico");
            this.iconsOnTaskbar.Images.SetKeyName(793, "search_laptop_4.ico");
            this.iconsOnTaskbar.Images.SetKeyName(794, "search_server.ico");
            this.iconsOnTaskbar.Images.SetKeyName(795, "search_web.ico");
            this.iconsOnTaskbar.Images.SetKeyName(796, "server_gear.ico");
            this.iconsOnTaskbar.Images.SetKeyName(797, "server_to_desktop.ico");
            this.iconsOnTaskbar.Images.SetKeyName(798, "server_window.ico");
            this.iconsOnTaskbar.Images.SetKeyName(799, "settings_gear.ico");
            this.iconsOnTaskbar.Images.SetKeyName(800, "settings_gear_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(801, "shell_window1.ico");
            this.iconsOnTaskbar.Images.SetKeyName(802, "shell_window2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(803, "shell_window3.ico");
            this.iconsOnTaskbar.Images.SetKeyName(804, "shell_window4.ico");
            this.iconsOnTaskbar.Images.SetKeyName(805, "shell_window5.ico");
            this.iconsOnTaskbar.Images.SetKeyName(806, "shell_window6.ico");
            this.iconsOnTaskbar.Images.SetKeyName(807, "shut_down_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(808, "shut_down_normal.ico");
            this.iconsOnTaskbar.Images.SetKeyName(809, "shut_down_with_computer.ico");
            this.iconsOnTaskbar.Images.SetKeyName(810, "sched_tasks.ico");
            this.iconsOnTaskbar.Images.SetKeyName(811, "signature.ico");
            this.iconsOnTaskbar.Images.SetKeyName(812, "signature_excl.ico");
            this.iconsOnTaskbar.Images.SetKeyName(813, "signature_no.ico");
            this.iconsOnTaskbar.Images.SetKeyName(814, "sndvol32_input.ico");
            this.iconsOnTaskbar.Images.SetKeyName(815, "sndvol32_main.ico");
            this.iconsOnTaskbar.Images.SetKeyName(816, "sndvol32_output.ico");
            this.iconsOnTaskbar.Images.SetKeyName(817, "SoundGrn.ico");
            this.iconsOnTaskbar.Images.SetKeyName(818, "SoundPu2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(819, "SoundPur.ico");
            this.iconsOnTaskbar.Images.SetKeyName(820, "SoundTel.ico");
            this.iconsOnTaskbar.Images.SetKeyName(821, "SoundVor.ico");
            this.iconsOnTaskbar.Images.SetKeyName(822, "SoundYel.ico");
            this.iconsOnTaskbar.Images.SetKeyName(823, "spider.ico");
            this.iconsOnTaskbar.Images.SetKeyName(824, "standby_monitor_moon.ico");
            this.iconsOnTaskbar.Images.SetKeyName(825, "standby_monitor_moon_cool.ico");
            this.iconsOnTaskbar.Images.SetKeyName(826, "start_menu_shortcuts.ico");
            this.iconsOnTaskbar.Images.SetKeyName(827, "start_menu_xp.ico");
            this.iconsOnTaskbar.Images.SetKeyName(828, "system_restore.ico");
            this.iconsOnTaskbar.Images.SetKeyName(829, "telephony.ico");
            this.iconsOnTaskbar.Images.SetKeyName(830, "template_directory_net_web.ico");
            this.iconsOnTaskbar.Images.SetKeyName(831, "template_empty.ico");
            this.iconsOnTaskbar.Images.SetKeyName(832, "template_nework_conn.ico");
            this.iconsOnTaskbar.Images.SetKeyName(833, "template_nework_places.ico");
            this.iconsOnTaskbar.Images.SetKeyName(834, "template_printer.ico");
            this.iconsOnTaskbar.Images.SetKeyName(835, "template_scanner_camera.ico");
            this.iconsOnTaskbar.Images.SetKeyName(836, "template_sched_task.ico");
            this.iconsOnTaskbar.Images.SetKeyName(837, "template_world.ico");
            this.iconsOnTaskbar.Images.SetKeyName(838, "themes.ico");
            this.iconsOnTaskbar.Images.SetKeyName(839, "time_and_date.ico");
            this.iconsOnTaskbar.Images.SetKeyName(840, "tip.ico");
            this.iconsOnTaskbar.Images.SetKeyName(841, "tools_gear.ico");
            this.iconsOnTaskbar.Images.SetKeyName(842, "tree.ico");
            this.iconsOnTaskbar.Images.SetKeyName(843, "true_type_paint.ico");
            this.iconsOnTaskbar.Images.SetKeyName(844, "trust0.ico");
            this.iconsOnTaskbar.Images.SetKeyName(845, "trust1_restrict.ico");
            this.iconsOnTaskbar.Images.SetKeyName(846, "tune-up.ico");
            this.iconsOnTaskbar.Images.SetKeyName(847, "unplug_eject_pc.ico");
            this.iconsOnTaskbar.Images.SetKeyName(848, "unplug_storage.ico");
            this.iconsOnTaskbar.Images.SetKeyName(849, "ups.ico");
            this.iconsOnTaskbar.Images.SetKeyName(850, "url1.ico");
            this.iconsOnTaskbar.Images.SetKeyName(851, "url1a.ico");
            this.iconsOnTaskbar.Images.SetKeyName(852, "url2.ico");
            this.iconsOnTaskbar.Images.SetKeyName(853, "usb.ico");
            this.iconsOnTaskbar.Images.SetKeyName(854, "usb_port.ico");
            this.iconsOnTaskbar.Images.SetKeyName(855, "user_calendar.ico");
            this.iconsOnTaskbar.Images.SetKeyName(856, "user_card.ico");
            this.iconsOnTaskbar.Images.SetKeyName(857, "user_card_view.ico");
            this.iconsOnTaskbar.Images.SetKeyName(858, "user_computer.ico");
            this.iconsOnTaskbar.Images.SetKeyName(859, "user_computer_pair.ico");
            this.iconsOnTaskbar.Images.SetKeyName(860, "user_network.ico");
            this.iconsOnTaskbar.Images.SetKeyName(861, "user_world.ico");
            this.iconsOnTaskbar.Images.SetKeyName(862, "users.ico");
            this.iconsOnTaskbar.Images.SetKeyName(863, "users_green.ico");
            this.iconsOnTaskbar.Images.SetKeyName(864, "users_key.ico");
            this.iconsOnTaskbar.Images.SetKeyName(865, "utopia_smiley.ico");
            this.iconsOnTaskbar.Images.SetKeyName(866, "video_.ico");
            this.iconsOnTaskbar.Images.SetKeyName(867, "video_compression.ico");
            this.iconsOnTaskbar.Images.SetKeyName(868, "video_gr.ico");
            this.iconsOnTaskbar.Images.SetKeyName(869, "video_mg.ico");
            this.iconsOnTaskbar.Images.SetKeyName(870, "video_mk.ico");
            this.iconsOnTaskbar.Images.SetKeyName(871, "video_tl.ico");
            this.iconsOnTaskbar.Images.SetKeyName(872, "web_file.ico");
            this.iconsOnTaskbar.Images.SetKeyName(873, "web_file_set.ico");
            this.iconsOnTaskbar.Images.SetKeyName(874, "wia_img_a.ico");
            this.iconsOnTaskbar.Images.SetKeyName(875, "wia_img_color.ico");
            this.iconsOnTaskbar.Images.SetKeyName(876, "wia_img_color_sound.ico");
            this.iconsOnTaskbar.Images.SetKeyName(877, "wia_img_gray.ico");
            this.iconsOnTaskbar.Images.SetKeyName(878, "wia_img_check.ico");
            this.iconsOnTaskbar.Images.SetKeyName(879, "window_red_hilights.ico");
            this.iconsOnTaskbar.Images.SetKeyName(880, "windows.ico");
            this.iconsOnTaskbar.Images.SetKeyName(881, "windows_button.ico");
            this.iconsOnTaskbar.Images.SetKeyName(882, "windows_movie.ico");
            this.iconsOnTaskbar.Images.SetKeyName(883, "windows_slanted.ico");
            this.iconsOnTaskbar.Images.SetKeyName(884, "windows_three.ico");
            this.iconsOnTaskbar.Images.SetKeyName(885, "windows_title.ico");
            this.iconsOnTaskbar.Images.SetKeyName(886, "windows_update_large.ico");
            this.iconsOnTaskbar.Images.SetKeyName(887, "windows_update_old.ico");
            this.iconsOnTaskbar.Images.SetKeyName(888, "windows_update_small.ico");
            this.iconsOnTaskbar.Images.SetKeyName(889, "winhelp_small_icons.png");
            this.iconsOnTaskbar.Images.SetKeyName(890, "WinRep.ico");
            this.iconsOnTaskbar.Images.SetKeyName(891, "winrep_mag_glass.ico");
            this.iconsOnTaskbar.Images.SetKeyName(892, "wm.ico");
            this.iconsOnTaskbar.Images.SetKeyName(893, "wm_file.ico");
            this.iconsOnTaskbar.Images.SetKeyName(894, "world.ico");
            this.iconsOnTaskbar.Images.SetKeyName(895, "world_address_book.ico");
            this.iconsOnTaskbar.Images.SetKeyName(896, "world_lock.ico");
            this.iconsOnTaskbar.Images.SetKeyName(897, "world_network_directories.ico");
            this.iconsOnTaskbar.Images.SetKeyName(898, "world_phonereceiver.ico");
            this.iconsOnTaskbar.Images.SetKeyName(899, "world_star.ico");
            this.iconsOnTaskbar.Images.SetKeyName(900, "write_card_phone.ico");
            this.iconsOnTaskbar.Images.SetKeyName(901, "write_file.ico");
            this.iconsOnTaskbar.Images.SetKeyName(902, "write_red.ico");
            this.iconsOnTaskbar.Images.SetKeyName(903, "write_wordpad.ico");
            this.iconsOnTaskbar.Images.SetKeyName(904, "write_yellow.ico");
            this.iconsOnTaskbar.Images.SetKeyName(905, "xml.ico");
            this.iconsOnTaskbar.Images.SetKeyName(906, "xml_gear.ico");
            this.iconsOnTaskbar.Images.SetKeyName(907, "salam.ico");
            this.iconsOnTaskbar.Images.SetKeyName(908, "cruel.ico");
            this.iconsOnTaskbar.Images.SetKeyName(909, "freecell.ico");
            this.iconsOnTaskbar.Images.SetKeyName(910, "golf.ico");
            this.iconsOnTaskbar.Images.SetKeyName(911, "paint.ico");
            this.iconsOnTaskbar.Images.SetKeyName(912, "pegged.ico");
            this.iconsOnTaskbar.Images.SetKeyName(913, "reversi.ico");
            this.iconsOnTaskbar.Images.SetKeyName(914, "snake.ico");
            this.iconsOnTaskbar.Images.SetKeyName(915, "tictac.ico");
            this.iconsOnTaskbar.Images.SetKeyName(916, "taipei.ico");
            this.iconsOnTaskbar.Images.SetKeyName(917, "tetris.ico");
            // 
            // taskbarIconsListView
            // 
            this.taskbarIconsListView.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.taskbarIconsListView.BackColor = System.Drawing.SystemColors.Control;
            this.taskbarIconsListView.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.taskbarIconsListView.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.columnHeader1});
            this.taskbarIconsListView.ForeColor = System.Drawing.Color.Black;
            this.taskbarIconsListView.FullRowSelect = true;
            this.taskbarIconsListView.GridLines = true;
            this.taskbarIconsListView.HeaderStyle = System.Windows.Forms.ColumnHeaderStyle.Nonclickable;
            this.taskbarIconsListView.HideSelection = false;
            this.taskbarIconsListView.LargeImageList = this.iconsOnTaskbar;
            this.taskbarIconsListView.Location = new System.Drawing.Point(69, 10);
            this.taskbarIconsListView.MultiSelect = false;
            this.taskbarIconsListView.Name = "taskbarIconsListView";
            this.taskbarIconsListView.Size = new System.Drawing.Size(633, 48);
            this.taskbarIconsListView.SmallImageList = this.iconsOnTaskbar;
            this.taskbarIconsListView.TabIndex = 1;
            this.taskbarIconsListView.UseCompatibleStateImageBehavior = false;
            this.taskbarIconsListView.DoubleClick += new System.EventHandler(this.taskbarIconsListView_DoubleClick);
            // 
            // columnHeader1
            // 
            this.columnHeader1.Text = "Window title";
            this.columnHeader1.Width = 200;
            // 
            // statusPanel
            // 
            this.statusPanel.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.statusPanel.Controls.Add(this.clockLabel);
            this.statusPanel.Location = new System.Drawing.Point(708, 10);
            this.statusPanel.Name = "statusPanel";
            this.statusPanel.Size = new System.Drawing.Size(89, 48);
            this.statusPanel.TabIndex = 2;
            this.statusPanel.Paint += new System.Windows.Forms.PaintEventHandler(this.statusPanel_Paint);
            // 
            // clockLabel
            // 
            this.clockLabel.AutoSize = true;
            this.clockLabel.Location = new System.Drawing.Point(15, 4);
            this.clockLabel.Name = "clockLabel";
            this.clockLabel.Size = new System.Drawing.Size(49, 13);
            this.clockLabel.TabIndex = 0;
            this.clockLabel.Text = "00:00:00";
            this.clockLabel.TextAlign = System.Drawing.ContentAlignment.TopCenter;
            // 
            // clockTimer
            // 
            this.clockTimer.Interval = 1000;
            this.clockTimer.Tick += new System.EventHandler(this.clockTimer_Tick);
            // 
            // configMenu
            // 
            this.configMenu.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.dockToolStripMenuItem,
            this.floatToolStripMenuItem,
            this.toolStripSeparator2,
            this.hideDesktopTaskPanelToolStripMenuItem,
            this.toolStripSeparator1,
            this.closeToolStripMenuItem});
            this.configMenu.Name = "configMenu";
            this.configMenu.Size = new System.Drawing.Size(199, 104);
            // 
            // dockToolStripMenuItem
            // 
            this.dockToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.topToolStripMenuItem,
            this.rightToolStripMenuItem,
            this.bottomToolStripMenuItem,
            this.leftToolStripMenuItem});
            this.dockToolStripMenuItem.Name = "dockToolStripMenuItem";
            this.dockToolStripMenuItem.Size = new System.Drawing.Size(198, 22);
            this.dockToolStripMenuItem.Text = "&Dock";
            // 
            // topToolStripMenuItem
            // 
            this.topToolStripMenuItem.Image = global::Win113.Shell.Properties.Resources.maximize;
            this.topToolStripMenuItem.Name = "topToolStripMenuItem";
            this.topToolStripMenuItem.Size = new System.Drawing.Size(114, 22);
            this.topToolStripMenuItem.Text = "&Top";
            this.topToolStripMenuItem.Click += new System.EventHandler(this.topToolStripMenuItem_Click);
            // 
            // rightToolStripMenuItem
            // 
            this.rightToolStripMenuItem.Image = global::Win113.Shell.Properties.Resources.right;
            this.rightToolStripMenuItem.Name = "rightToolStripMenuItem";
            this.rightToolStripMenuItem.Size = new System.Drawing.Size(114, 22);
            this.rightToolStripMenuItem.Text = "&Right";
            this.rightToolStripMenuItem.Click += new System.EventHandler(this.rightToolStripMenuItem_Click);
            // 
            // bottomToolStripMenuItem
            // 
            this.bottomToolStripMenuItem.Image = global::Win113.Shell.Properties.Resources.minimize;
            this.bottomToolStripMenuItem.Name = "bottomToolStripMenuItem";
            this.bottomToolStripMenuItem.Size = new System.Drawing.Size(114, 22);
            this.bottomToolStripMenuItem.Text = "&Bottom";
            this.bottomToolStripMenuItem.Click += new System.EventHandler(this.bottomToolStripMenuItem_Click);
            // 
            // leftToolStripMenuItem
            // 
            this.leftToolStripMenuItem.Image = global::Win113.Shell.Properties.Resources.left;
            this.leftToolStripMenuItem.Name = "leftToolStripMenuItem";
            this.leftToolStripMenuItem.Size = new System.Drawing.Size(114, 22);
            this.leftToolStripMenuItem.Text = "&Left";
            this.leftToolStripMenuItem.Click += new System.EventHandler(this.leftToolStripMenuItem_Click);
            // 
            // floatToolStripMenuItem
            // 
            this.floatToolStripMenuItem.Name = "floatToolStripMenuItem";
            this.floatToolStripMenuItem.Size = new System.Drawing.Size(198, 22);
            this.floatToolStripMenuItem.Text = "&Float";
            this.floatToolStripMenuItem.Click += new System.EventHandler(this.floatToolStripMenuItem_Click);
            // 
            // toolStripSeparator2
            // 
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new System.Drawing.Size(195, 6);
            // 
            // hideDesktopTaskPanelToolStripMenuItem
            // 
            this.hideDesktopTaskPanelToolStripMenuItem.Name = "hideDesktopTaskPanelToolStripMenuItem";
            this.hideDesktopTaskPanelToolStripMenuItem.Size = new System.Drawing.Size(198, 22);
            this.hideDesktopTaskPanelToolStripMenuItem.Text = "&Hide desktop TaskPanel";
            this.hideDesktopTaskPanelToolStripMenuItem.Click += new System.EventHandler(this.hideDesktopTaskPanelToolStripMenuItem_Click);
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(195, 6);
            // 
            // closeToolStripMenuItem
            // 
            this.closeToolStripMenuItem.Name = "closeToolStripMenuItem";
            this.closeToolStripMenuItem.Size = new System.Drawing.Size(198, 22);
            this.closeToolStripMenuItem.Text = "&Close";
            this.closeToolStripMenuItem.Click += new System.EventHandler(this.closeToolStripMenuItem_Click);
            // 
            // StartButton
            // 
            this.StartButton.BackgroundImage = global::Win113.Shell.Properties.Resources.winstart;
            this.StartButton.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.StartButton.FlatAppearance.BorderSize = 0;
            this.StartButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.StartButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(238)));
            this.StartButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.StartButton.ImageKey = "(none)";
            this.StartButton.Location = new System.Drawing.Point(5, 10);
            this.StartButton.Name = "StartButton";
            this.StartButton.Size = new System.Drawing.Size(58, 22);
            this.StartButton.TabIndex = 0;
            this.StartButton.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.StartButton.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.StartButton.UseVisualStyleBackColor = true;
            this.StartButton.Click += new System.EventHandler(this.StartButton_Click);
            this.StartButton.Paint += new System.Windows.Forms.PaintEventHandler(this.StartButton_Paint);
            this.StartButton.MouseDown += new System.Windows.Forms.MouseEventHandler(this.StartButton_MouseDown);
            this.StartButton.MouseUp += new System.Windows.Forms.MouseEventHandler(this.StartButton_MouseUp);
            // 
            // closeButton
            // 
            this.closeButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left)));
            this.closeButton.FlatAppearance.BorderSize = 0;
            this.closeButton.FlatStyle = System.Windows.Forms.FlatStyle.Popup;
            this.closeButton.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(238)));
            this.closeButton.ImageAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.closeButton.ImageKey = "(none)";
            this.closeButton.Location = new System.Drawing.Point(5, 36);
            this.closeButton.Name = "closeButton";
            this.closeButton.Size = new System.Drawing.Size(58, 22);
            this.closeButton.TabIndex = 3;
            this.closeButton.Text = "&Config";
            this.closeButton.TextImageRelation = System.Windows.Forms.TextImageRelation.ImageBeforeText;
            this.closeButton.UseVisualStyleBackColor = true;
            this.closeButton.Click += new System.EventHandler(this.closeButton_Click);
            this.closeButton.Paint += new System.Windows.Forms.PaintEventHandler(this.closeButton_Paint);
            this.closeButton.MouseDown += new System.Windows.Forms.MouseEventHandler(this.closeButton_MouseDown);
            this.closeButton.MouseUp += new System.Windows.Forms.MouseEventHandler(this.closeButton_MouseUp);
            // 
            // TaskbarForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 61);
            this.Controls.Add(this.StartButton);
            this.Controls.Add(this.closeButton);
            this.Controls.Add(this.statusPanel);
            this.Controls.Add(this.taskbarIconsListView);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.MinimumSize = new System.Drawing.Size(65, 61);
            this.Name = "TaskbarForm";
            this.ShowIcon = false;
            this.ShowInTaskbar = false;
            this.StartPosition = System.Windows.Forms.FormStartPosition.Manual;
            this.Text = "Win113.Taskbar";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.Taskbar_FormClosing);
            this.FormClosed += new System.Windows.Forms.FormClosedEventHandler(this.Taskbar_FormClosed);
            this.Load += new System.EventHandler(this.TaskbarForm_Load);
            this.Shown += new System.EventHandler(this.Taskbar_Shown);
            this.ResizeEnd += new System.EventHandler(this.TaskbarForm_ResizeEnd);
            this.Resize += new System.EventHandler(this.Taskbar_Resize);
            this.statusPanel.ResumeLayout(false);
            this.statusPanel.PerformLayout();
            this.configMenu.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Win113.Shell.Components.NoSelectButton StartButton;
        private System.Windows.Forms.ImageList iconsOnTaskbar;
        private System.Windows.Forms.ListView taskbarIconsListView;
        private System.Windows.Forms.Panel statusPanel;
        private System.Windows.Forms.ColumnHeader columnHeader1;
        private Win113.Shell.Components.NoSelectButton closeButton;
        private System.Windows.Forms.Timer clockTimer;
        private System.Windows.Forms.Label clockLabel;
        private System.Windows.Forms.ContextMenuStrip configMenu;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripMenuItem closeToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem dockToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem topToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem bottomToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem leftToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem rightToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem floatToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
        private System.Windows.Forms.ToolStripMenuItem hideDesktopTaskPanelToolStripMenuItem;
    }
}

